name: Unity Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Unity
      uses: actions/setup-unity@v1
      with:
        unityVersion: 2021.3.27f1
        serial: ${{ secrets.UNITY_SERIAL }}
        modules: "Unity,Windows Build Support" # Windows Build Support を追加

    - name: Run tests
      run: unity -runTests -projectPath ./work/CaseStudy -testPlatform playmode

    - name: Check test results
      if: failure()
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const github = context.repo;
          const prNumber = context.payload.pull_request.number;
          github.pulls.update({
            owner: github.owner,
            repo: github.repo,
            pull_number: prNumber,
            body: "Tests failed. Please fix the issues before merging.",
            state: "closed"
          });
